### PR TITLE
add mailto link for sponsor us button

### LINKED ISSUE #35: Include mail to for Sponsor Us

### PR DESCRIPTION
**Pull request by suneettipirneni**
Closes #35

### CODE REVIEW

**Comment by aileenpongnon** [comment]
i was planning on restyling this to be 2 buttons in a row similar to how shellhacks does it, since you have this part of the PR done do you want to include the join us button? 
Screen Shot 2021-09-12 at 11 09 14 PM

**Review by aileenpongnon — APPROVED** [review]

**Comment by suneettipirneni** [comment]
> i was planning on restyling this to be 2 buttons in a row similar to how shellhacks does it, since you have this part of the PR done do you want to include the join us button?
> Screen Shot 2021-09-12 at 11 09 14 PM

Will do

**Comment by aileenpongnon** [comment]
complete for review

**Review by habraham2023 — APPROVED** [review]
Not sure if this was by design or not but the register button doesn't make a shimmer animation on it, other than that LGTM!

**Comment by aileenpongnon** [comment]
> Not sure if this was by design or not but the register button doesn't make a shimmer animation on it, other than that LGTM!

it was by design but in hindsight it doesn't look that good. i'm hesitant on adding shimmer to register cause I feel like it may be overkill

**Pull request merged**
